app = "stella-fuyjjg"
primary_region = "syd"
kill_timeout = 120
kill_signal = "SIGTERM"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 80
min_machines_running = 0
processes = [ "app" ]

[[vm]]
size = "shared-cpu-1x"
memory = "256mb"
memory_mb = 256
