# fly.toml app configuration file generated for stella-fuyjjg on 2024-12-08T01:12:37Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "stella-fuyjjg"
primary_region = "syd"
kill_timeout = 120
kill_signal = "SIGTERM"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 80
min_machines_running = 0
processes = [ "app" ]

[[vm]]
size = "shared-cpu-1x"
memory = "256mb"
memory_mb = 256